### ISSUE TITLE
Support rescore

### ISSUE THREAD

**Issue by ghost** [fullscale/elastic.js#21] opened 2013-05-02 19:23 UTC
Need to add support for rescoring, which can be very helpful for in my case, wildcard queries to limit down by rescoring with a phrase query, to bubble up better matches.

http://www.elasticsearch.org/guide/reference/api/search/rescore/

**Comment by mattweber** [comment] 2013-05-06 18:58
Dupe of pull request issue.

**Closed as completed by mattweber** 2013-05-06 18:58 UTC
